<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\TBdPerson */

$this->title = $model->FID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tbd People'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tbd-person-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->FID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->FID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'FID',
            'FIDNUM',
            'FNAME_L1',
            'FNAME_L2',
            'FNAME_L3',
            'FNUMBER',
            'FDESCRIPTION_L1',
            'FDESCRIPTION_L2',
            'FDESCRIPTION_L3',
            'FSIMPLENAME',
            'FGENDER',
            'FBIRTHDAY',
            'FEMAIL:email',
            'FADDRESS_L1',
            'FADDRESS_L2',
            'FADDRESS_L3',
            'FSTATE',
            'FHOMEPHONE',
            'FOFFICEPHONE',
            'FCELL',
            'FBACKUPCELL',
            'FBACKUPEMAIL:email',
            'FRTX',
            'FIDCARDNO',
            'FIDCARDADRESS_L1',
            'FIDCARDADRESS_L2',
            'FIDCARDADRESS_L3',
            'FPASSPORTNO',
            'FOLDNAME_L1',
            'FOLDNAME_L2',
            'FOLDNAME_L3',
            'FHEIGHT',
            'FNATIVEPLACE_L1',
            'FNATIVEPLACE_L2',
            'FNATIVEPLACE_L3',
            'FBLOODTYPE',
            'FCREATORID',
            'FCREATETIME',
            'FLASTUPDATEUSERID',
            'FLASTUPDATETIME',
            'FKACLASSFICATIONID',
            'FWEDID',
            'FHEALTHID',
            'FPOLITICALFACEID',
            'FSTANDINGID',
            'FFOLKID',
            'FBIRTHID',
            'FCONTROLUNITID',
            'FHRORGUNITID',
            'FRESIDENCEPLACE',
            'FLENOFACTUALSERVICE',
            'FEMPLOYEETYPEID',
            'FHIGHESTTECHPOSTID',
            'FHIGHESTDEGREEID',
            'FEMPLOYEECLASSIFYID',
            'FDELETEDSTATUS',
            'FLCMRATIONLEVELID',
            'FNATIONALITYID',
            'FCHECKSTATE',
            'FINDEX',
            'FEMPLOYTECHPOSTID',
            'FHIGHESTSUBDEGREEID',
            'FZDY1',
            'FZDY2',
            'FZDY3',
            'FZDY4',
            'FZDY5',
            'FZDY6',
            'FZDY7',
            'FZDY8',
            'FZDY9',
            'FZDY10',
            'FZDY11',
            'FZDY12',
            'FZDY13',
            'FZDY14',
            'FZDY15',
            'FZDY16',
            'FZDY17',
            'FZDY18',
            'FZDY19',
            'FZDY20',
            'FZDY21',
            'FZDY22',
            'FZDY23',
            'FZDY24',
            'FZDY25',
            'FZDY26',
            'FFULLNAMEPINGYIN',
            'FSIMPLENAMEPINGYIN',
            'FISSTANDBY',
            'FISSTANDBYCADRE',
            'FHIGHESTCOMPETENCYID',
            'FNAMEPINYIN',
            'FNAMESHORTPINYIN',
            'FREGRESIDENCEID',
            'FHJADDRESS',
            'FIDCARDADDRESS',
            'FHOMEPLACE',
            'FEFFDT',
            'FLEFFDT',
            'FHISTORYRELATEID',
            'FIDCARDBEGINDATE',
            'FIDCARDENDDATE',
            'FEXTENDFIELDNUMONE',
            'FPROTOCOL',
            'FIDCARDISSUEORG',
            'CFTC',
            'CFTSRYBSID',
            'CFFXDW',
            'CFGATXZ',
            'CFPTTXZ',
            'CFISJZZ',
            'CFJHSYQKID',
            'CFZVCSNY',
            'CFISGG',
            'CFISQB',
            'CFSBGXDW',
            'CFYHKXX',
            'CFISXSCT',
            'CFRDYZNX',
            'CFSXRQ',
            'CFJFSXRQ',
            'CFJFNX',
            'CFJFJZRQ',
            'CFGZD',
            'CFRDTSJ',
        ],
    ]) ?>

</div>
